# Generated by Django 4.2.24 on 2025-09-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patientprofile_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyse',
            name='heatmap_img',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='irm_original',
            field=models.ImageField(blank=True, null=True, upload_to='irm/'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='probabilities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyse',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='maladie',
            field=models.CharField(default='Alzheimer', max_length=100),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='type_analyse',
            field=models.CharField(default='MRI', max_length=50),
        ),
    ]
