# Generated by Django 4.2.24 on 2025-09-15 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analyse_confidence_analyse_heatmap_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='biomarkers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyse',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.doctorprofile'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyse',
            name='xai_visualisation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='type_analyse',
            field=models.CharField(choices=[('MRI', 'IRM'), ('BIOMARKER', 'Biomarqueurs'), ('COMBINED', 'IRM + Biomarqueurs')], default='MRI', max_length=20),
        ),
    ]
