# Generated by Django 4.2.24 on 2025-09-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_analyse_biomarkers_analyse_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='xai_visualisation',
        ),
        migrations.AddField(
            model_name='analyse',
            name='xai_biomarkers',
            field=models.ImageField(blank=True, null=True, upload_to='xai_biomarkers/'),
        ),
    ]
