# Generated by Django 4.2.24 on 2025-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_analyse_xai_visualisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='type_analyse',
            field=models.CharField(choices=[('MRI', 'IRM'), ('BIOMARKER', 'Biomarkers'), ('COMBINED_ALZ', 'MRI + Biomarkers'), ('DATSCAN', 'DaTscan'), ('COMBINED_PARK', 'DaTscan + Biomarkers'), ('CLINICAL_DATA', 'Clinical data')], default='MRI', max_length=20),
        ),
    ]
