# Generated by Django 4.2.26 on 2025-11-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_analyse_type_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='shap_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
